/**
 * @module features/scan/parseScannedQR
 *
 * Pure classification of whatever string comes back from the camera. One
 * scanner has to serve three unrelated flows — add a friend, join a group,
 * check in to an activity — and the only thing distinguishing them is the
 * shape of the payload.
 *
 * Lives here rather than inside `app/scan.tsx` so it can actually be tested:
 * the mobile vitest setup is pure-logic only (`environment: 'node'`, no RN
 * transform), so anything importing `expo-camera` is unreachable to it. Same
 * move as `features/activity/attendeeRoster.ts`, and for the same reason —
 * that bug shipped because the logic was welded to a screen.
 *
 * The routing ORDER is part of the contract, not an implementation detail, so
 * it lives in `classifyScannedQR` where a test can pin it.
 */

/** What the scanned payload turned out to be. */
export type ScannedQR =
  /** Friend invite — send a friend request to this user. */
  | { kind: 'friend'; userId: string }
  /** Group invite — join using this 8-character code. */
  | { kind: 'group'; inviteCode: string }
  /** An activity's `qrCode` token — check in with it verbatim. */
  | { kind: 'checkin'; qrCode: string }
  /** Understood the envelope, but it is unusable. Tell the user, don't guess. */
  | { kind: 'invalid' };

/** Parse `data` as JSON, returning null unless it yields a plain object. */
const asObject = (data: string): Record<string, any> | null => {
  try {
    const parsed = JSON.parse(data);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
};

/**
 * Friend QR. Canonical format is `sc:friend:<userId>`; the JSON and deep-link
 * forms are still accepted because codes generated by older builds may already
 * be printed or sitting in someone's camera roll.
 *
 * @returns the userId, or null if this isn't a friend QR at all.
 */
export const parseFriendQR = (data: string): string | null => {
  const canonical = data.match(/^sc:friend:([\w-]+)$/);
  if (canonical) return canonical[1];

  const parsed = asObject(data);
  if (parsed) {
    if (parsed.type === 'friend' || parsed.userId) {
      return parsed.userId || parsed.id || null;
    }
    return null;
  }

  // Legacy deep link, e.g. `app://add-friend?userId=u-7`. Only reachable when
  // the payload isn't JSON — a JSON friend payload is handled above.
  if (data.includes('add-friend') || data.includes('userId')) {
    const match = data.match(/userId[=:'"\s]+([^&"'\s}]+)/i);
    if (match && match[1]) return match[1];
  }

  return null;
};

/**
 * Group-invite QR, as produced by the backend's `generateGroupInviteQR`:
 * `{ type: 'GROUP_INVITE', groupId, inviteCode, generatedAt }`.
 *
 * `generatedAt` is deliberately ignored — nothing validates it server-side, so
 * treating it as an expiry here would only be theatre.
 *
 * @returns the invite code, or null if this isn't a group-invite QR.
 */
export const parseGroupInviteQR = (data: string): string | null => {
  const parsed = asObject(data);
  if (parsed?.type === 'GROUP_INVITE' && parsed.inviteCode) {
    return String(parsed.inviteCode);
  }
  return null;
};

/**
 * Decide what a scanned string means.
 *
 * Order matters and is asserted in the tests:
 *   1. friend  — most specific, has a canonical prefix of its own
 *   2. group   — a tagged JSON envelope
 *   3. invalid — a structured payload we recognise but can't use, OR any JSON
 *                object we don't recognise at all
 *   4. checkin — the fallback, because an activity's `qrCode` is a bare
 *                `uuidv4()` with no structure to match on
 *
 * Step 3 is why an unrecognised JSON blob does NOT become a check-in attempt.
 * It used to: scanning a group's own invite QR fell through to
 * `checkinWithQR(<the JSON>)` and the user was told "Invalid QR code. Activity
 * not found" — an activity error for a group action (TEST_FINDINGS F7). Since
 * a real check-in token is always a bare UUID, JSON here can never be one, so
 * sending it would be a request guaranteed to fail with a misleading message.
 */
export const classifyScannedQR = (raw: string): ScannedQR => {
  const data = (raw ?? '').trim();
  if (!data) return { kind: 'invalid' };

  const userId = parseFriendQR(data);
  if (userId) return { kind: 'friend', userId };

  const inviteCode = parseGroupInviteQR(data);
  if (inviteCode) return { kind: 'group', inviteCode };

  // A JSON object that got this far is a payload we understand the shape of
  // but cannot act on (e.g. GROUP_INVITE with no inviteCode), or one we don't
  // understand at all. Either way it is not a check-in token.
  if (asObject(data)) return { kind: 'invalid' };

  return { kind: 'checkin', qrCode: data };
};

export default classifyScannedQR;
